# Generated by Django 5.0.2 on 2025-06-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='points',
            field=models.JSONField(default=list),
        ),
    ]
